@baseUrl = http://localhost:7080

### Get nonce
POST {{baseUrl}}/api/authenticate/attestation/getNonce
Content-Type: application/json

{
  "UserId": "27771117319151770",
  "Nonce": "your_platform_nonce_here"
}

###

### Mothership Auth
POST {{baseUrl}}/api/authenticate/attestation/mothershipAuth
Content-Type: application/json
X-Device-Model: Oculus Quest 3 (eureka)

{
  "UserId": "27771117319151770",
  "AttestationToken": "YOUR_TOKEN_HERE"
}

###

### Photon Auth
POST {{baseUrl}}/api/photon-auth
Content-Type: application/json

{
  "MetaUser": "Julienvrthegoat",
  "OculusId": "25680854384906657",
  "PlayFabId": "7C04ED4D5DFEF8E0",
  "OrgScopedId": "26613156158307036",
  "Method": "GET"
}

###
